apiVersion: v1
kind: Secret
metadata:
  name: {{ include "logward.secretsName" . }}
  labels:
    {{- include "logward.labels" . | nindent 4 }}
type: Opaque
data:
  {{- $jwtSecret := .Values.config.jwtSecret | default (randAlphaNum 64) }}
  JWT_SECRET: {{ $jwtSecret | b64enc | quote }}
  {{- $sessionSecret := .Values.config.sessionSecret | default (randAlphaNum 64) }}
  SESSION_SECRET: {{ $sessionSecret | b64enc | quote }}
  {{- if and .Values.config.smtp.enabled (not .Values.config.smtp.existingSecret) }}
  SMTP_USER: {{ .Values.config.smtp.user | b64enc | quote }}
  SMTP_PASSWORD: {{ .Values.config.smtp.password | b64enc | quote }}
  {{- end }}
---
{{- if .Values.timescaledb.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "logward.fullname" . }}-timescaledb
  labels:
    {{- include "logward.timescaledb.labels" . | nindent 4 }}
type: Opaque
data:
  {{- $dbPassword := .Values.timescaledb.auth.password | default (randAlphaNum 32) }}
  password: {{ $dbPassword | b64enc | quote }}
  {{- $postgresPassword := .Values.timescaledb.auth.postgresPassword | default (randAlphaNum 32) }}
  postgres-password: {{ $postgresPassword | b64enc | quote }}
{{- end }}
---
{{- if .Values.redis.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "logward.fullname" . }}-redis
  labels:
    {{- include "logward.redis.labels" . | nindent 4 }}
type: Opaque
data:
  {{- $redisPassword := .Values.redis.auth.password | default (randAlphaNum 32) }}
  password: {{ $redisPassword | b64enc | quote }}
{{- end }}
---
{{- if and (not .Values.timescaledb.enabled) (not .Values.externalDatabase.existingSecret) .Values.externalDatabase.host }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "logward.fullname" . }}-external-db
  labels:
    {{- include "logward.labels" . | nindent 4 }}
type: Opaque
data:
  password: {{ .Values.externalDatabase.password | b64enc | quote }}
{{- end }}
---
{{- if and (not .Values.redis.enabled) (not .Values.externalRedis.existingSecret) .Values.externalRedis.host }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "logward.fullname" . }}-external-redis
  labels:
    {{- include "logward.labels" . | nindent 4 }}
type: Opaque
data:
  password: {{ .Values.externalRedis.password | b64enc | quote }}
{{- end }}
